name: Master Codecov Report

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  report-coverage:
    runs-on: dimerun-k3-ubuntu2204

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v3

      - name: Build for test
        run: pnpm -r build:test

      - name: Test
        run: pnpm ci:test

      - name: Codecov Core
        uses: codecov/codecov-action@v3
        with:
          flags: core
          directory: ./packages/core

      - name: Codecov UI
        uses: codecov/codecov-action@v3
        with:
          flags: experience
          directory: ./packages/experience
